# Generated by Django 5.2.2 on 2025-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['brand', 'model']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='consumption',
            field=models.FloatField(),
        ),
    ]
