# Generated by Django 5.2.2 on 2025-07-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_booking_options_alter_car_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджено'), ('canceled', 'Скасовано')], default='pending', max_length=20),
        ),
    ]
